# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 01 Oct 2017 09:48:31 +0000
*               @ALL          1
*               @user         8
