<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: mike
 * Date: Sun, 01 Oct 2017 13:35:04 +0200
 */

$conf['title'] = 'EasyFlow';
$conf['license'] = 'gnufdl';
$conf['youarehere'] = 1;
$conf['tocminheads'] = '0';
$conf['maxtoclevel'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
